import "./AppHeader.css";

export function AppHeader({ activeView, scheduleCount, programCount }) {
  const isScheduleView = activeView === "SCHEDULE";

  return (
    <header className="page-header">
      <div>
        <p className="eyebrow">Media Scheduler</p>
        <h1>{isScheduleView ? "This Week" : "Your Library"}</h1>
        <p className="page-description">
          {isScheduleView
            ? "A weekly lineup generated by the backend: one movie and two TV shows for each day."
            : "Browse the movies and TV shows currently available to the scheduler. Posters, reviews, and richer metadata can drop into this layout when the backend starts returning them."}
        </p>
      </div>

      <div className="library-summary">
        <span>{isScheduleView ? scheduleCount : programCount}</span>
        <p>{isScheduleView ? "days planned" : "programs loaded"}</p>
      </div>
    </header>
  );
}